### ISSUE TITLE
Keep developing it!!!

### ISSUE THREAD

**Issue by SrijanSriv211** [willmexe/Game-Engine#3]
Nice engine, even i'm developing one using Pygame, [Hexa](https://github.com/Light-Lens/Hexa), you can check it out (if you want). I haven't updated my repo from a really long time because i'm reworking the whole engine and improving it. The only feedback i would like to give you is to keep developing it!

**Comment by dinkelspiel** [comment]
This project has been replaced by [this game engine](https://github.com/willmexe/Game-Engine-CS).
